[2020-07-16 16:44:31,520] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.csv_to_db2 2020-07-16T11:13:21.402423+00:00 [queued]>
[2020-07-16 16:44:31,533] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.csv_to_db2 2020-07-16T11:13:21.402423+00:00 [queued]>
[2020-07-16 16:44:31,534] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-16 16:44:31,534] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-07-16 16:44:31,534] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-16 16:44:31,857] {taskinstance.py:900} INFO - Executing <Task(BashOperator): csv_to_db2> on 2020-07-16T11:13:21.402423+00:00
[2020-07-16 16:44:31,875] {standard_task_runner.py:53} INFO - Started process 705977 to run task
[2020-07-16 16:44:32,297] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: storing_data.csv_to_db2 2020-07-16T11:13:21.402423+00:00 [running]> bhakti-Vostro-3558
[2020-07-16 16:44:32,316] {taskinstance.py:1145} ERROR - csv_to_db2.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 964, in _run_raw_task
    self.render_templates(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1426, in render_templates
    self.task.render_template_fields(context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 716, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 723, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 750, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: csv_to_db2.sh
[2020-07-16 16:44:32,321] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-07-16 16:44:41,367] {logging_mixin.py:112} INFO - [2020-07-16 16:44:41,366] {local_task_job.py:103} INFO - Task exited with return code 1
