[2020-07-18 17:00:00,364] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.mysql_status 2020-07-18T11:29:21.864769+00:00 [queued]>
[2020-07-18 17:00:00,382] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.mysql_status 2020-07-18T11:29:21.864769+00:00 [queued]>
[2020-07-18 17:00:00,382] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-18 17:00:00,383] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-07-18 17:00:00,383] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-18 17:00:00,521] {taskinstance.py:900} INFO - Executing <Task(BashOperator): mysql_status> on 2020-07-18T11:29:21.864769+00:00
[2020-07-18 17:00:00,526] {standard_task_runner.py:53} INFO - Started process 151866 to run task
[2020-07-18 17:00:00,961] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: storing_data.mysql_status 2020-07-18T11:29:21.864769+00:00 [running]> bhakti-Vostro-3558
[2020-07-18 17:00:00,987] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-07-18 17:00:00,989] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmpdhwmjp6e/mysql_status6bwykv62
[2020-07-18 17:00:00,989] {bash_operator.py:115} INFO - Running command: #!/bin/bash -x
user=root
password=
dbname=airflow_db2
airflow_condition=123
root_dir="/home/bhakti/airflow/"
location=$root_dir"input_data/dump_mysql_db.db"
if [ $airflow_condition -ne " " ]
then
docker exec -it mysqlCon \
mysqldump --user $user --databases $dbname > $location
python3 $root_dir"minioconnect/minio_connection.py"
echo 'File uploaded successfully'
else
  echo 'something went wrong'
fi
[2020-07-18 17:00:01,002] {bash_operator.py:122} INFO - Output:
[2020-07-18 17:00:01,005] {bash_operator.py:126} INFO - /tmp/airflowtmpdhwmjp6e/mysql_status6bwykv62: line 8: [:  : integer expression expected
[2020-07-18 17:00:01,005] {bash_operator.py:126} INFO - something went wrong
[2020-07-18 17:00:01,006] {bash_operator.py:128} INFO - Command exited with return code 0
[2020-07-18 17:00:01,019] {taskinstance.py:1052} INFO - Marking task as SUCCESS.dag_id=storing_data, task_id=mysql_status, execution_date=20200718T112921, start_date=20200718T113000, end_date=20200718T113001
[2020-07-18 17:00:10,219] {logging_mixin.py:112} INFO - [2020-07-18 17:00:10,218] {local_task_job.py:103} INFO - Task exited with return code 0
