[2020-07-17 15:13:43,930] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.mysql_status 2020-07-17T09:39:58.727561+00:00 [queued]>
[2020-07-17 15:13:43,942] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.mysql_status 2020-07-17T09:39:58.727561+00:00 [queued]>
[2020-07-17 15:13:43,942] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-17 15:13:43,943] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-07-17 15:13:43,943] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-17 15:13:44,091] {taskinstance.py:900} INFO - Executing <Task(BashOperator): mysql_status> on 2020-07-17T09:39:58.727561+00:00
[2020-07-17 15:13:44,099] {standard_task_runner.py:53} INFO - Started process 524075 to run task
[2020-07-17 15:13:44,423] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: storing_data.mysql_status 2020-07-17T09:39:58.727561+00:00 [running]> bhakti-Vostro-3558
[2020-07-17 15:13:44,440] {taskinstance.py:1145} ERROR - /mysql_dump.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 964, in _run_raw_task
    self.render_templates(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1426, in render_templates
    self.task.render_template_fields(context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 716, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 723, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 750, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /mysql_dump.sh
[2020-07-17 15:13:44,444] {taskinstance.py:1174} INFO - All retries failed; marking task as FAILED.dag_id=storing_data, task_id=mysql_status, execution_date=20200717T093958, start_date=20200717T094343, end_date=20200717T094344
[2020-07-17 15:13:53,804] {logging_mixin.py:112} INFO - [2020-07-17 15:13:53,804] {local_task_job.py:103} INFO - Task exited with return code 1
