[2020-07-18 12:58:18,947] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.mysql_status 2020-07-18T07:27:48.730539+00:00 [queued]>
[2020-07-18 12:58:18,957] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.mysql_status 2020-07-18T07:27:48.730539+00:00 [queued]>
[2020-07-18 12:58:18,957] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-18 12:58:18,957] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-07-18 12:58:18,957] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-18 12:58:19,096] {taskinstance.py:900} INFO - Executing <Task(BashOperator): mysql_status> on 2020-07-18T07:27:48.730539+00:00
[2020-07-18 12:58:19,102] {standard_task_runner.py:53} INFO - Started process 46621 to run task
[2020-07-18 12:58:19,365] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: storing_data.mysql_status 2020-07-18T07:27:48.730539+00:00 [running]> bhakti-Vostro-3558
[2020-07-18 12:58:19,414] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-07-18 12:58:19,416] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmp54ddfeaw/mysql_statush24woll2
[2020-07-18 12:58:19,416] {bash_operator.py:115} INFO - Running command: #!/bin/bash -x
user=root
dbname=airflow_db2
location='/home/bhakti/airflow/input_data/dump_mysql_db.db'
docker exec -it mysqlCon \
mysqldump --user $user --databases $dbname > $location
python3 '/home/bhakti/airflow/minioconnect/minio_connection.py'
[2020-07-18 12:58:19,430] {bash_operator.py:122} INFO - Output:
[2020-07-18 12:58:21,442] {bash_operator.py:126} INFO - Traceback (most recent call last):
[2020-07-18 12:58:21,443] {bash_operator.py:126} INFO -   File "/home/bhakti/airflow/minioconnect/minio_connection.py", line 10, in <module>
[2020-07-18 12:58:21,443] {bash_operator.py:126} INFO -     bucket_file_name = file_name + date
[2020-07-18 12:58:21,443] {bash_operator.py:126} INFO - TypeError: can only concatenate str (not "type") to str
[2020-07-18 12:58:21,588] {bash_operator.py:128} INFO - Command exited with return code 1
[2020-07-18 12:58:21,596] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-07-18 12:58:21,598] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-07-18 12:58:28,768] {logging_mixin.py:112} INFO - [2020-07-18 12:58:28,767] {local_task_job.py:103} INFO - Task exited with return code 1
