[2020-07-17 16:09:43,531] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.mysql_status 2020-07-17T10:38:51.941961+00:00 [queued]>
[2020-07-17 16:09:43,542] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.mysql_status 2020-07-17T10:38:51.941961+00:00 [queued]>
[2020-07-17 16:09:43,542] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-17 16:09:43,542] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-07-17 16:09:43,542] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-17 16:09:43,697] {taskinstance.py:900} INFO - Executing <Task(BashOperator): mysql_status> on 2020-07-17T10:38:51.941961+00:00
[2020-07-17 16:09:43,703] {standard_task_runner.py:53} INFO - Started process 614102 to run task
[2020-07-17 16:09:43,876] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: storing_data.mysql_status 2020-07-17T10:38:51.941961+00:00 [running]> bhakti-Vostro-3558
[2020-07-17 16:09:43,891] {taskinstance.py:1145} ERROR - /mysql_dump.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 964, in _run_raw_task
    self.render_templates(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1426, in render_templates
    self.task.render_template_fields(context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 716, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 723, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/baseoperator.py", line 750, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /mysql_dump.sh
[2020-07-17 16:09:43,983] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-07-17 16:09:53,416] {logging_mixin.py:112} INFO - [2020-07-17 16:09:53,416] {local_task_job.py:103} INFO - Task exited with return code 1
